CI: Pin Rust to 1.43.0 for Python builds
Something in 1.44.0 (released 2020-06-04) broke the Windows build,
resulting in an error like:

    undefined reference to `_Unwind_Resume'

We already build with `panic=abort`.
For now this will reenable working builds until we figure out what's
broken.