Bug 1982711 - Glean Health Ping with directory info before and after init (#3221)
* Bug 1982711 - Add Glean `health` ping and metrics

* Add post_init health ping

* Send internal metrics in 'health' ping

Updated various internal metrics to include 'health' in their send_in_pings lists, ensuring they are also reported in the health ping. Also removed unused Deserialize derives and minor code cleanup.

* Update collected-metrics.md

* Update metrics.yaml and pings.yaml with data-review link

* WIP - fixing python tests

This commit isn't complete, the remaining errors are:

```
FAILED glean-core/python/tests/test_glean.py::test_presubmit_makes_a_valid_ping - AssertionError: assert 'preinit_ping' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_client_activity_api - AssertionError: assert 'baseline' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_max_events_overflow - AssertionError: assert 'events' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_glean_shutdown - AssertionError: assert 10 == 12
FAILED glean-core/python/tests/test_glean.py::test_uploader_capabilities_reported - AssertionError: assert 'store1' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_uploader_capabilities_empty_not_reported - AssertionError: assert 'store1' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_uploader_capabilities_in_send_if_empty_ping - AssertionError: assert 'store1' == 'health'
FAILED glean-core/python/tests/test_glean.py::test_uploader_capabilities_in_empty_ping - Failed: DID NOT RAISE <class 'TimeoutError'>
FAILED glean-core/python/tests/test_glean.py::test_uploader_capabilities_in_events_ping - AssertionError: assert 'custom-events' == 'health'
FAILED glean-core/python/tests/test_network.py::test_recording_upload_errors_doesnt_clobber_database - AssertionError: assert 1 == 3
========================================================= 10 failed, 140 passed, 1 skipped, 1 warning in 72.89s (0:01:12) =========================================================
make: *** [test-python] Error 1
```

* update tests

* attempt to fix test failing on CI only

* fix rlb thread-crashing test

* update shell tests

* Add protection and instrumentation on directory unwrap failures

* Don't collect directory info or send health ping if internal pings are disabled

* Move dir-errors to the directory info object metric

* Address change requests

* Change health_ping test app id

---------

Co-authored-by: Charlie Humphreys <chumphreys@mozilla.com>